// vue-app/src/components/SeasonBadge.vue
<script setup lang="ts">
import type { SeasonBadge } from 'shared-types'
import { onMounted, useTemplateRef, watchEffect } from 'vue'

interface SeasonBadgeProps {
  open: boolean
  loading: boolean
  seasonBadge?: SeasonBadge | null
}

const { seasonBadge, loading, open } = defineProps<SeasonBadgeProps>()
const emit = defineEmits(['close'])

const dialog = useTemplateRef('dialog')

watchEffect(() => {
  if (open && dialog.value) {
    dialog.value.showModal()
  }
})

const handleClose = () => {
  emit('close')

  if (dialog.value) {
    dialog.value.close()
  }
}
</script>

<template>
  <dialog class="SeasonBadgeDisplay" ref="dialog">
    <button class="SeasonBadgeDisplay__CloseButton" @click="handleClose">
      ×
    </button>
    <div class="SeasonBadgeDisplay__Content">
      <div v-if="loading" class="SeasonBadgeDisplay__Loading Loading">
        Loading...
      </div>
      <img
        v-else-if="!!seasonBadge"
        class="SeasonBadgeDisplay__Image"
        :src="seasonBadge.badge"
        :alt="seasonBadge.season"
      />
    </div>
  </dialog>
</template>

// react-app/src/components/SeasonBadge.tsx
import React from 'react'
import type { SeasonBadge as SeasonBadgeType } from 'shared-types'

interface SeasonBadgeProps {
  open: boolean
  onClose: () => void
  loading: boolean
  seasonBadge: SeasonBadgeType
}

export const SeasonBadge = ({
  seasonBadge,
  open,
  loading,
  onClose,
}: SeasonBadgeProps) => {
  const ref = React.useRef<HTMLDialogElement>(null)

  React.useEffect(() => {
    if (open && ref.current) {
      ref.current.showModal()
    }
  }, [open])

  const handleClose = () => {
    onClose()
    if (ref.current) {
      ref.current.close()
    }
  }

  return (
    <dialog className="SeasonBadgeDisplay" ref={ref}>
      <button className="SeasonBadgeDisplay__CloseButton" onClick={handleClose}>
        ×
      </button>
      <div className="SeasonBadgeDisplay__Content">
        {loading ? (
          <div className="SeasonBadgeDisplay__Loading Loading">Loading...</div>
        ) : (
          seasonBadge && (
            <img
              className="SeasonBadgeDisplay__Image"
              src={seasonBadge.badge}
              alt={seasonBadge.season}
            />
          )
        )}
      </div>
    </dialog>
  )
}
