// react-app/src/components/LeagueList.tsx
import { usePresenter } from '../hooks/usePresenter'
import { LeaguesPresenter } from 'features'
import { League } from './League.tsx'
import type { SportType } from 'shared-types'
import { SeasonBadge } from './SeasonBadge.tsx'

export const LeagueList = () => {
  const [viewModel, presenter] = usePresenter(LeaguesPresenter)

  const sportTypeFilterOptions: SportType[] = [
    'American Football',
    'Basketball',
    'Soccer',
    'Ice Hockey',
    'Motorsport',
  ]

  return (
    <div className="LeagueList">
      <h2 className="LeagueList__Title">Sport Leagues</h2>

      {viewModel.loading ? (
        <div className="LeagueList__Loading Loading">Loading...</div>
      ) : (
        <>
          <div className="LeagueList__Filters">
            <input
              id="search-input"
              type="text"
              placeholder="Search leagues"
              value={viewModel.searchQuery}
              className="LeagueList__Search"
              onChange={(e) => presenter.setSearchQuery(e.target.value)}
            />
            <select
              id="sport-type-filter"
              className="LeagueList__SportTypeFilter"
              value={viewModel.sportTypeFilter}
              onChange={(e) => {
                presenter.setSportTypeFilter(e.target.value as SportType)
              }}
            >
              <option value={''}>All</option>
              <optgroup label="Sport Type">
                {sportTypeFilterOptions.map((sportTypeFilterOption) => (
                  <option
                    key={sportTypeFilterOption}
                    value={sportTypeFilterOption}
                  >
                    {sportTypeFilterOption}
                  </option>
                ))}
              </optgroup>
            </select>
          </div>
          {viewModel.leagues.length === 0 ? (
            <div className="LeagueList__NoResults">🤷 No leagues found</div>
          ) : (
            <div className="LeagueList__Leagues">
              {viewModel.leagues.map((league) => (
                <League
                  key={league.id}
                  alternateNames={league.alternateName.split(',')}
                  onClick={() => presenter.openSeasonBadgeDisplay(league.id)}
                  {...league}
                />
              ))}
            </div>
          )}
        </>
      )}

      <SeasonBadge
        open={viewModel.isBadgeDisplayOpen}
        loading={viewModel.seasonBadgeLoading}
        seasonBadge={viewModel.currentBadge}
        onClose={() => presenter.closeSeasonBadgeDisplay()}
      />
    </div>
  )
}

// vue-app/src/components/LeagueList.vue
<script setup lang="ts">
import { usePresenter } from '../composables/usePresenter'
import { LeaguesPresenter } from 'features'
import type { SportType } from 'shared-types'
import League from './League.vue'
import SeasonBadge from './SeasonBadge.vue'

const [viewModel, presenter] = usePresenter(LeaguesPresenter)

const sportTypeFilterOptions: SportType[] = [
  'American Football',
  'Basketball',
  'Soccer',
  'Ice Hockey',
  'Motorsport',
]
</script>

<template>
  <div class="LeagueList">
    <h2 class="LeagueList__Title">Sport Leagues</h2>

    <div v-if="viewModel.loading" class="LeagueList__Loading Loading">
      Loading...
    </div>
    <template v-else>
      <div class="LeagueList__Filters">
        <input
          id="search-input"
          type="text"
          placeholder="Search leagues"
          :value="viewModel.searchQuery"
          class="LeagueList__Search"
          @input="
            presenter.setSearchQuery(($event.target as HTMLInputElement).value)
          "
        />
        <select
          id="sport-type-filter"
          class="LeagueList__SportTypeFilter"
          :value="viewModel.sportTypeFilter"
          @change="
            presenter.setSportTypeFilter(
              ($event.target as HTMLSelectElement).value as SportType,
            )
          "
        >
          <option value="">All</option>
          <optgroup label="Sport Type">
            <option
              v-for="sportTypeFilterOption in sportTypeFilterOptions"
              :key="sportTypeFilterOption"
              :value="sportTypeFilterOption"
            >
              {{ sportTypeFilterOption }}
            </option>
          </optgroup>
        </select>
      </div>
      <div v-if="viewModel.leagues.length === 0" class="LeagueList__NoResults">
        🤷 No leagues found
      </div>
      <div v-else class="LeagueList__Leagues">
        <League
          v-for="league in viewModel.leagues"
          :key="league.id"
          :id="league.id"
          :name="league.name"
          :sport="league.sport"
          :alternate-names="league.alternateName.split(',')"
          @click="presenter.openSeasonBadgeDisplay(league.id)"
        />
      </div>
    </template>

    <SeasonBadge
      :open="viewModel.isBadgeDisplayOpen"
      :loading="viewModel.seasonBadgeLoading"
      :season-badge="viewModel.currentBadge"
      @close="presenter.closeSeasonBadgeDisplay()"
    />
  </div>
</template>
